# based off https://github.com/pgroonga/pgroonga/blob/master/.travis.yml
language: c
matrix:
  include:

#   - env:
#       PG_VERSION: 9.2
#     addons:
#       postgresql: "9.2"
#   - env:
#       PG_VERSION: 9.3
#     addons:
#       postgresql: "9.3"
#   - env:
#       PG_VERSION: 9.4
#     addons:
#       postgresql: "9.4"
#   - env:
#       PG_VERSION: 9.5
#     addons:
#       postgresql: "9.5"
#   - env:
#       PG_VERSION: 9.6
#       WAL_SUPPORTED: "yes"
#     addons:
#       postgresql: "9.6"
     - env:
         PG_VERSION: 10
       addons:
         postgresql: "10"


sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-${PG_VERSION}
  - sudo apt-get install -qq -y postgresql-client-${PG_VERSION}
  - sudo service postgresql restart

before_script:
  - sudo make install
  - make installcheck

#script:
#  - sudo -u postgres -H mkdir -p /tmp/space
#    PG_REGRESS_DIFF_OPTS="-u" \
#      make installcheck \
#        TMP_DIR=/tmp \
#        SETUP_TMP_DIR=no \
#        EXTRA_REGRESS_OPTS="--launcher=$(pwd)/test/short-pgappname"
#  - |
#
after_failure:
  - cat regression.diffs
